require "rubygems"
require "rake"
require "rake/clean"

EXECUTABLE = "build/Release/CelerityViewer.app"

CLEAN << 'build'

desc 'Build CelerityViewer.app'
task :build do
  sh "xcodebuild"
end

desc "Run #{EXECUTABLE}"
task :run do
  sh "open #{EXECUTABLE}"
end

desc 'Install CelerityViewer.app to /Applications'
task :install => %w[build] do
  mv EXECUTABLE, "/Applications", :verbose => true
end

desc 'Try sending a web page to the socket'
task :try_socket do
  require 'socket'
  require "open-uri"
  require "iconv"
  
  html = Iconv.conv("utf-8", "iso-8859-1", open("http://www.finn.no/").read)
  p :html => html
  s = TCPSocket.new("localhost", 6429)
  s.write html
  s.close
end

desc 'Build and run'
task :default => %w[build run]

